In [32]:
import pandas as pd 

df_all_games = pd.read_csv('data/games.csv')
df_one_row_per_game = pd.read_csv('data/one-row-per-game.csv')

In [33]:
df_all_games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22024,1610612738,BOS,Boston Celtics,22401187,2025-04-13,BOS vs. CHA,W,241,93,...,0.692,15,34,49,22,12,6,13,14,7.0
1,22024,1610612747,LAL,Los Angeles Lakers,22401199,2025-04-13,LAL @ POR,L,239,81,...,0.714,13,29,42,21,9,11,20,21,-28.0
2,22024,1610612759,SAS,San Antonio Spurs,22401197,2025-04-13,SAS vs. TOR,W,240,125,...,0.875,9,41,50,22,11,2,12,13,7.0
3,22024,1610612754,IND,Indiana Pacers,22401189,2025-04-13,IND @ CLE,W,289,126,...,0.909,14,47,61,27,15,10,13,20,8.0
4,22024,1610612760,OKC,Oklahoma City Thunder,22401196,2025-04-13,OKC @ NOP,W,241,115,...,0.889,17,37,54,16,8,4,10,25,15.0

In [34]:
df_one_row_per_game.head()

,GAME_ID,GAME_DATE,HOME_TEAM,PTS_home,AWAY_TEAM,PTS_away,IS_NEUTRAL,HOME_WIN,HOME_MARGIN
0,22401187,2025-04-13,BOS,93,CHA,86,False,1,7
1,22401197,2025-04-13,SAS,125,TOR,118,False,1,7
2,22401196,2025-04-13,NOP,100,OKC,115,False,0,-15
3,22401190,2025-04-13,MIA,118,WAS,119,False,0,-1
4,22401189,2025-04-13,CLE,118,IND,126,False,0,-8

In [35]:
win_pct_df = df_all_games.groupby('TEAM_ABBREVIATION')['WL'].apply(lambda x: (x=='W').mean())
win_pct_df

TEAM_ABBREVIATION
ATL    0.487805
BKN    0.317073
BOS    0.743902
CHA    0.231707
CHI    0.475610
CLE    0.780488
DAL    0.475610
DEN    0.609756
DET    0.536585
GSW    0.585366
HOU    0.634146
IND    0.609756
LAC    0.609756
LAL    0.609756
MEM    0.585366
MIA    0.451220
MIL    0.585366
MIN    0.597561
NOP    0.256098
NYK    0.621951
OKC    0.829268
ORL    0.500000
PHI    0.292683
PHX    0.439024
POR    0.439024
SAC    0.487805
SAS    0.414634
TOR    0.365854
UTA    0.207317
WAS    0.219512
Name: WL, dtype: float64

In [36]:
df_one_row_per_game["HOME_TEAM_win_pct"] = df_one_row_per_game['HOME_TEAM'].map(win_pct_df)
df_one_row_per_game["AWAY_TEAM_win_pct"] = df_one_row_per_game['AWAY_TEAM'].map(win_pct_df)

In [37]:
df_one_row_per_game.head()

,GAME_ID,GAME_DATE,HOME_TEAM,PTS_home,AWAY_TEAM,PTS_away,IS_NEUTRAL,HOME_WIN,HOME_MARGIN,HOME_TEAM_win_pct,AWAY_TEAM_win_pct
0,22401187,2025-04-13,BOS,93,CHA,86,False,1,7,0.743902,0.231707
1,22401197,2025-04-13,SAS,125,TOR,118,False,1,7,0.414634,0.365854
2,22401196,2025-04-13,NOP,100,OKC,115,False,0,-15,0.256098,0.829268
3,22401190,2025-04-13,MIA,118,WAS,119,False,0,-1,0.451220,0.219512
4,22401189,2025-04-13,CLE,118,IND,126,False,0,-8,0.780488,0.609756

In [38]:
df_one_row_per_game["pred"] = df_one_row_per_game["HOME_TEAM_win_pct"] >= df_one_row_per_game["AWAY_TEAM_win_pct"]
df_one_row_per_game.head()

,GAME_ID,GAME_DATE,HOME_TEAM,PTS_home,AWAY_TEAM,PTS_away,IS_NEUTRAL,HOME_WIN,HOME_MARGIN,HOME_TEAM_win_pct,AWAY_TEAM_win_pct,pred
0,22401187,2025-04-13,BOS,93,CHA,86,False,1,7,0.743902,0.231707,True
1,22401197,2025-04-13,SAS,125,TOR,118,False,1,7,0.414634,0.365854,True
2,22401196,2025-04-13,NOP,100,OKC,115,False,0,-15,0.256098,0.829268,False
3,22401190,2025-04-13,MIA,118,WAS,119,False,0,-1,0.451220,0.219512,True
4,22401189,2025-04-13,CLE,118,IND,126,False,0,-8,0.780488,0.609756,True

In [39]:
(df_one_row_per_game["pred"] == df_one_row_per_game["HOME_WIN"]).mean()

np.float64(0.7)

In [41]:
df_all_games["GAME_DATE"]

0       2025-04-13
1       2025-04-13
2       2025-04-13
3       2025-04-13
4       2025-04-13
           ...
2455    2024-10-23
2456    2024-10-22
2457    2024-10-22
2458    2024-10-22
2459    2024-10-22
Name: GAME_DATE, Length: 2460, dtype: str